### ISSUE TITLE
Run with CUDA Toolkit 7.

### ISSUE THREAD

**Issue by CsatiZoltan** [ramakarl/fluids3#2]
I cannot run it under 64 bit Windows 7, bacause cudart32_50_35.dll is missing. Could you please compile it on CUDA Toolkit 7 or send me that missing dll? Thanks.

**Comment by ramakarl** [comment]
Hi, 
You are welcome to compile it with CUDA 7.0, or download the archived CUDA 5.0. At present, I don't have time to recompile Fluids v.3. At http://fluids3.com you will also find forums where others discuss building and using fluids v.3.

**Comment by GiantCowFilms** [comment]
I had same issue, it would be lovely if you could fix it.

**Comment by baehny** [comment]
The packed binaries from http://www.rchoetzlein.com/fluids3/?page_id=13 come with a cudart32_42_9.dll.
I simply copied the file and renamed it to cudart32_50_35.dll to make it work. I don't know if this has some side effects but this works for me. I have only the newest CUDA SDKs 9.0 and 9.1 on my machine.

**Comment by CsatiZoltan** [comment]
@baehny  Thanks, it works in that way.
