### ISSUE TITLE
Question: how to make fluids3 look more like "real water"?

### ISSUE THREAD

**Issue by sensboston** [ramakarl/fluids3#6]
I know, you don't have time for fuids3 development but maybe you can provide a quick tip: how to make fluids3 particles more like real water? I mean, maybe, changing particles color and opacity (make em bluish and semi-transparent) and apply some post effect to the final scene will make render looks more realistic?

I know, NVIDIA has perfect water demo (I already tried and it's perfect) but will be great to have ability to build similar effect at home :)

**Comment by ramakarl** [comment]
Hi,

We will be releasing a new SDK soon called GVDB Voxels.
Included in this release will be a sample, gFluidSurface, which fully 
integrates Fluid v.3 and also performs water surfacing interactively 
using voxels and raytracing. If  you would like to try it early, you can 
join the GVDB Beta program here:
   http://developer.nvidia.com/gvdb
Then click on "Register for early access".. once approved, you will get 
access to the code and samples.

That sample is near real-time, but not quite suitable for gaming as it 
is intended for motion pictures and can handle much larger volumes with 
more flexibility. If you want fluids for gaming, try out Cataclysm. 
(https://developer.nvidia.com/cataclysm-flip-solver-gpu-particles)

Regards,
  Rama

**Comment by sensboston** [comment]
Thanks a lot for suggestion, Rama! Just filled the application and (I hope so) it will be approved. It will be really interesting to run some exciting samples on my GTX 1070 and uncover full power of this prefect video card :)

**Comment by sensboston** [comment]
Hi Rama, I tried GVDB demos (compiled & works fine on my PC) but I can tell you: your fluids3 is much more impressive than any GVDB demo! It's a really nice app and great way to demonstrate modern NVIDIA's accelerators power!
