### ISSUE TITLE
Found a fix for the particle clustering

### ISSUE THREAD

**Issue by asbjornlystrup** [ramakarl/fluids3#8]
Hi, thank you so much for sharing this with everyone! It has been a great learning experience while porting it over to the Unity engine. I looked into the problem of particle clustering and I think I figured out the bug. I'm still quite new to this, so correct me if I'm wrong or you have a reason behind the code being this way.

The fix: In the "contributePressure" function in "fluid_system_kern.cu", just remove the " && dsq > 0.0" part in the distance check.

This avoids particles flying out of control and clustering to each other unnaturally. It also seems to make the distribution of particles at the surface uniform with the rest of the body; before it had a higher concentration of particles at the surface. The reason I believe this " && dsq > 0.0" check is a bug, apart from the results after the fix looking more natural, is that ignoring a particle's own mass when calculating the density at its spot just is physically incorrect (again, correct me if I'm wrong and there's a reason behind this in this particular case). When many particles are around, the density converges to a more natural value, but when few particles are around it becomes pretty unnatural. Take for example a cluster of two particles. One particle will only consider the other's mass for density, not its own, which is kind of strange when you think about it.

**Comment by ramakarl** [comment]
This is a great find, thanks!
I've committed the fix to main branch.
